# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

### VM Setup variables
BOX            = "jgabriel/ubuntu-20.04" # You can search for boxes at https://vagrantcloud.com/search
CPU            = "2"
PORT_FORWARD   = "80"
RAM            = "1024"
DIR_HOST       = "../../scripts"
DIR_GUEST      = "/vagrant_data"

# Locale
ENV["LC_ALL"] = "en_US.UTF-8"

### Cluster Swarm
swarm = {
  "node1" => { :hostname => "node1", :ip => "192.168.100.210", :host => "8080" },
  "node2" => { :hostname => "node2", :ip => "192.168.100.220", :host => "8081" },
  "node3" => { :hostname => "node3", :ip => "192.168.100.230", :host => "8082" }
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   swarm.each_with_index do |(node, i), index|
     config.vm.define node do |box|
       box.vm.box              = (BOX)
       box.vm.hostname         = "#{i[:hostname]}"
       box.vm.box_version      = "1.0" 
       box.vm.network "private_network", ip: "#{i[:ip]}"
       box.vm.network "forwarded_port", guest:"80", host:"#{i[:host]}"
       box.vm.synced_folder (DIR_HOST), (DIR_GUEST)
      
       box.vm.provider "virtualbox" do |vb|
         vb.gui    = false
         vb.cpus   = (CPU)
         vb.memory = (RAM)
       end
       config.vm.provision "shell", path: "../../scripts/boot-strap.sh"
       config.vm.provision "shell", path: "../../scripts/docker-install.sh"
     end
   end
end
